In [31]:
import numpy as np
import pandas as pd

from math import sqrt
import proj_1_newtons as p1

In [2]:
a = 1/sqrt(2)*np.array([1,0,1])



In [3]:
l2_norm = np.linalg.norm(a)

In [4]:
l2_norm


0.9999999999999999

In [5]:
x = np.array([1,2,3]).T
x

array([1, 2, 3])

In [6]:
np.transpose(x)*x

array([1, 4, 9])

In [29]:
x = [[1,2], 
    [3,4]]
theta = [1,1]
x = np.array(x)
theta = np.array(theta).T


In [9]:
np.outer(x[0], theta)

array([[1, 1],
       [2, 2]])

In [30]:
res = hessian(x, theta)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
d

In [11]:
res

0.22559538770208767

In [12]:
tmp = np.dot(x[0].T, x[0])

In [13]:
first_row = x[0, :]

# Step 2: Reshape the first row into a column vector (shape (n, 1))
z = first_row.reshape(-1, 1)

# Step 3: Compute z * z^T (shape (n, n))
result = np.dot(z, z.T)

print(result)

[[1 2]
 [2 4]]


In [14]:
x

array([[1, 2],
       [3, 4]])

In [15]:
# Ax = b



In [16]:
# xTAx 

In [17]:
# innner product xTy

# outer product xxT 

In [18]:
#in numpy python, i want to do the following: * first, define x and y, which are 3 x1 vectors with random values * define A, a 3 x3 matrix with random values * calculate x transpose y, the inner product * calculate xxT, the outer product * calculate Ax, the matrix multiplied by a vector

In [19]:

# Set random seed for reproducibility
np.random.seed(42)

# Define x and y as 3x1 vectors with random values
# x = np.random.rand(3, 1)
x = np.random.randint(0, 10, size=(3, 1))
y = np.random.rand(3, 1)

# Define A as a 3x3 matrix with random values
A = np.random.rand(3, 3)

# Calculate inner product (x transpose * y)
# Result is a scalar (1x1)
inner_product = x.T @ y  # alternatively: np.dot(x.T, y)

ip = np.dot(x.T, y)

# Calculate outer product (x * x transpose)
# Result is a 3x3 matrix
outer_product = x @ x.T  # alternatively: np.outer(x.flatten(), x.flatten())
op = np.outer(x, x.T)

# Calculate matrix-vector product (A * x)
# Result is a 3x1 vector
matrix_vector_product = A @ x  # alternatively: np.dot(A, x)


print("ip: ", ip)
print("op: ", op)

ip:  [[5.15196847]]
op:  [[36 18 42]
 [18  9 21]
 [42 21 49]]


In [20]:
# Print results
print("Vector x:")
print(x)
print("\nVector y:")
print(y)
print("\nMatrix A:")
print(A)
print("\nInner product (x^T * y):")
print(inner_product)
print("\nOuter product (x * x^T):")
print(outer_product)
print("\nMatrix-vector product (A * x):")
print(matrix_vector_product)

Vector x:
[[6]
 [3]
 [7]]

Vector y:
[[0.59865848]
 [0.15601864]
 [0.15599452]]

Matrix A:
[[0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]]

Inner product (x^T * y):
[[5.15196847]]

Outer product (x * x^T):
[[36 18 42]
 [18  9 21]
 [42 21 49]]

Matrix-vector product (A * x):
[[ 7.15483519]
 [11.09955791]
 [ 6.90444795]]
